server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
eureka.datacenter: cloud
eureka.environment: product